name: noteme
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  http: ^1.1.0
  lottie: ^2.6.0
  get: ^4.6.5
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.1
  flutter_advanced_switch: ^3.0.1
  firebase_core: ^2.22.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
