name: noteme
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
<<<<<<< HEAD
  google_fonts: ^6.1.0
  intl: ^0.18.1
  http: ^1.1.0
  lottie: ^2.6.0
  get: ^4.6.5
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.1
  flutter_advanced_switch: ^3.0.1
  firebase_core: ^2.22.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.14.0
=======
  google_fonts: ^5.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  get: ^4.6.5
  cloud_firestore: ^4.8.4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_advanced_switch: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1
>>>>>>> 75d05f9b86c7e77e973131dbd695befd4b9b6428

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
